name: Setup Workflow
description: Base setup for all workflows

runs:
  using: "composite"
  steps:
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: 17
        cache: 'gradle'

    - uses: gradle/gradle-build-action@v2
      with:
          cache-read-only: false
          cache-overwrite-existing: true
          gradle-home-cache-cleanup: true

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Accept licenses
      run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true
      shell: bash

