[versions]
androidx-activity-activity-compose-version = "1.7.0-alpha03"
androidx-annotation-version = "1.6.0-alpha01"
androidx-arch-core-core-testing-version = "2.2.0-alpha01"
androidx-compose-bom-version = "2023.01.00"
androidx-compose-compiler-version = "1.4.0"
androidx-core-core-ktx-version = "1.9.0-beta01"
androidx-datastore-version = "1.1.0-dev01"
androidx-hilt-hilt-navigation-compose-version = "1.1.0-alpha01"
androidx-lifecycle-lifecycle-version = "2.6.0-alpha04"
androidx-navigation-navigation-safe-args-gradle-plugin-version = "2.6.0-alpha04"
androidx-navigation-version = "2.6.0-alpha04"
androidx-room-version = "2.5.0"
androidx-test-core-ktx-version = "1.5.0"
androidx-test-espresso-espresso-core-version = "3.5.1"
androidx-test-ext-junit-version = "1.1.5"
app-cash-turbine-turbine-version = "0.12.1"
app-compat-version = "1.7.0-alpha01"
catalog-plugin-version = "0.7.0"
com-android-tools-build-gradle-version = "8.1.0-alpha01"
com-google-android-material-version = "1.8.0-rc01"
com-google-dagger-version = "2.44.2"
com-google-protobuf-java-lite-version = "4.0.0-rc-2"
com-google-protobuf-plugin-version = "0.9.1"
com-google-protobuf-version = "21.0-rc-1"
com-jakewharton-retrofit-retrofit2-kotlin-coroutines-adapter-version = "0.9.2"
com-jakewharton-retrofit-retrofit2-kotlinx-serialization-converter-version = "0.8.0"
com-jakewharton-timber-version = "5.0.1"
com-squareup-okhttp3-version = "5.0.0-alpha.9"
com-squareup-okio-version = "3.3.0"
com-squareup-retrofit2-retrofit-version = "2.9.0"
io-mockk-version = "1.13.3"
junit-version = "4.13.2"
org-jetbrains-kotlin-kotlin-gradle-plugin-version = "1.8.0"
org-jetbrains-kotlin-kotlin-serialization-gradle-plugin-version = "1.8.0"
org-jetbrains-kotlinx-kotlinx-coroutines-test-version = "1.6.4"
org-jetbrains-kotlinx-kotlinx-coroutines-version = "1.6.4"
org-jetbrains-kotlinx-kotlinx-serialization-json-version = "1.4.1"
org-jlleitschuh-gradle-ktlint-version = "11.0.0"
org-junit-jupiter-junit-jupiter-version = "5.9.1"
org-robolectric-robolectric-version = "4.9.2"
versions-plugin-version = "0.44.0"

[libraries]
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-activity-compose-version" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation-version" }
androidx-app-compat = { module = "androidx.appcompat:appcompat", version.ref = "app-compat-version" }
androidx-arch-core-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch-core-core-testing-version" }
androidx-compose-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom-version" }
androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-window-sizeclass = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-runtime-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-core-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-core-ktx-version" }
androidx-datastore-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore-version" }
androidx-hilt-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt-hilt-navigation-compose-version" }
androidx-lifecycle-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle-lifecycle-version" }
androidx-lifecycle-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle-lifecycle-version" }
androidx-lifecycle-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-lifecycle-version" }
androidx-lifecycle-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle-lifecycle-version" }
androidx-navigation-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation-version" }
androidx-navigation-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation-version" }
androidx-navigation-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation-navigation-safe-args-gradle-plugin-version" }
androidx-navigation-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation-version" }
androidx-room-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room-version" }
androidx-room-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room-version" }
androidx-room-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room-version" }
androidx-room-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room-version" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test-core-ktx-version" }
androidx-test-espresso-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso-espresso-core-version" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext-junit-version" }
app-cash-turbine-turbine = { module = "app.cash.turbine:turbine", version.ref = "app-cash-turbine-turbine-version" }
com-android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "com-android-tools-build-gradle-version" }
com-google-android-material = { module = "com.google.android.material:material", version.ref = "com-google-android-material-version" }
com-google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "com-google-dagger-version" }
com-google-dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "com-google-dagger-version" }
com-google-dagger-hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "com-google-dagger-version" }
com-google-protobuf-protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "com-google-protobuf-java-lite-version" }
com-google-protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "com-google-protobuf-version" }
com-jakewharton-retrofit-retrofit2-kotlin-coroutines-adapter = { module = "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter", version.ref = "com-jakewharton-retrofit-retrofit2-kotlin-coroutines-adapter-version" }
com-jakewharton-retrofit-retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "com-jakewharton-retrofit-retrofit2-kotlinx-serialization-converter-version" }
com-jakewharton-timber = { module = "com.jakewharton.timber:timber", version.ref = "com-jakewharton-timber-version" }
com-squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "com-squareup-okhttp3-version" }
com-squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "com-squareup-okhttp3-version" }
com-squareup-okio = { module = "com.squareup.okio:okio", version.ref = "com-squareup-okio-version" }
com-squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "com-squareup-retrofit2-retrofit-version" }
io-mockk = { module = "io.mockk:mockk", version.ref = "io-mockk-version" }
junit = { module = "junit:junit", version.ref = "junit-version" }
org-jetbrains-kotlin-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin-kotlin-gradle-plugin-version" }
org-jetbrains-kotlin-kotlin-serialization-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "org-jetbrains-kotlin-kotlin-serialization-gradle-plugin-version" }
org-jetbrains-kotlinx-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx-kotlinx-coroutines-version" }
org-jetbrains-kotlinx-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx-kotlinx-coroutines-version" }
org-jetbrains-kotlinx-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "org-jetbrains-kotlinx-kotlinx-coroutines-test-version" }
org-jetbrains-kotlinx-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "org-jetbrains-kotlinx-kotlinx-serialization-json-version" }
org-junit-jupiter-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "org-junit-jupiter-junit-jupiter-version" }
org-robolectric-robolectric = { module = "org.robolectric:robolectric", version.ref = "org-robolectric-robolectric-version" }

[bundles]
compose = [
    "androidx-compose-material3-material3",
    "androidx-compose-runtime-runtime",
    "androidx-compose-ui-ui",
    "androidx-lifecycle-lifecycle-runtime-compose",
]
coroutines = [
    "org-jetbrains-kotlinx-kotlinx-coroutines-android",
    "org-jetbrains-kotlinx-kotlinx-coroutines-core",
]
lifecycle = [
    "androidx-lifecycle-lifecycle-common-java8",
    "androidx-lifecycle-lifecycle-viewmodel-ktx",
]
okhttp = [
    "com-squareup-okhttp3-logging-interceptor",
    "com-squareup-okhttp3-okhttp",
    "com-squareup-okio",
]
retrofit = [
    "com-jakewharton-retrofit-retrofit2-kotlin-coroutines-adapter",
    "com-jakewharton-retrofit-retrofit2-kotlinx-serialization-converter",
    "com-squareup-retrofit2-retrofit",
]

[plugins]
com-github-ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin-version" }
com-google-protobuf = { id = "com.google.protobuf", version.ref = "com-google-protobuf-plugin-version" }
nl-littlerobots-version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "catalog-plugin-version" }
org-jlleitschuh-gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "org-jlleitschuh-gradle-ktlint-version" }
