[versions]
versions-plugin-version = "0.42.0"
catalog-plugin-version = "0.3.1"
androidx-core-core-ktx-version = "1.9.0-alpha01"
app-compat-version = "1.6.0-alpha01"
androidx-navigation-version = "2.5.0-alpha03"
androidx-lifecycle-lifecycle-viewmodel-ktx-version = "2.5.0-alpha04"
androidx-lifecycle-lifecycle-common-java8-version = "2.5.0-alpha04"
com-google-android-material-version = "1.6.0-beta01"
androidx-datastore-version = "1.0.0"
com-google-protobuf-java-lite-version = "4.0.0-rc-2"
androidx-hilt-version = "1.0.0"
com-google-dagger-version = "2.41"
com-squareup-okhttp3-version = "5.0.0-alpha.4"
com-squareup-okio-version = "3.0.0"
com-jakewharton-retrofit-retrofit2-kotlin-coroutines-adapter-version = "0.9.2"
com-jakewharton-retrofit-retrofit2-kotlinx-serialization-converter-version = "0.8.0"
com-squareup-retrofit2-retrofit-version = "2.9.0"
com-jakewharton-timber-version = "5.0.1"
androidx-test-ext-junit-version = "1.1.4-alpha03"
junit-version = "4.13.2"
androidx-test-espresso-espresso-core-version = "3.5.0-alpha03"
org-jetbrains-kotlinx-version = "1.6.0"
org-jetbrains-kotlinx-kotlinx-serialization-json-version = "1.3.2"
org-jetbrains-kotlinx-kotlinx-coroutines-test-version = "1.4.3"
androidx-hilt-hilt-navigation-compose-version = "1.0.0-alpha03"
androidx-compose-version = "1.2.0-alpha03"
androidx-activity-activity-compose-version = "1.3.0-alpha06"
com-android-tools-build-gradle-version = "7.3.0-alpha07"
org-jetbrains-kotlin-kotlin-gradle-plugin-version = "1.6.10"
com-google-protobuf-version = "0.8.12"
androidx-arch-core-core-testing-version = "2.1.0"
io-mockk-version = "1.11.0"
androidx-annotation-version = "1.3.0"

[libraries]
androidx-core-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-core-ktx-version" }
androidx-app-compat = { module = "androidx.appcompat:appcompat", version.ref = "app-compat-version" }
androidx-navigation-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation-version" }
androidx-navigation-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation-version" }
androidx-lifecycle-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-lifecycle-viewmodel-ktx-version" }
androidx-lifecycle-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle-lifecycle-common-java8-version" }
com-google-android-material = { module = "com.google.android.material:material", version.ref = "com-google-android-material-version" }
androidx-datastore-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore-version"}
com-google-protobuf-protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "com-google-protobuf-java-lite-version" }
androidx-hilt-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt-version" }
com-google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "com-google-dagger-version" }
com-google-dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "com-google-dagger-version" }
com-google-dagger-hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "com-google-dagger-version" }
com-squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "com-squareup-okhttp3-version" }
com-squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "com-squareup-okhttp3-version" }
com-squareup-okio = { module = "com.squareup.okio:okio", version.ref = "com-squareup-okio-version" }
com-jakewharton-retrofit-retrofit2-kotlin-coroutines-adapter = { module = "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter", version.ref = "com-jakewharton-retrofit-retrofit2-kotlin-coroutines-adapter-version" }
com-jakewharton-retrofit-retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "com-jakewharton-retrofit-retrofit2-kotlinx-serialization-converter-version" }
com-jakewharton-timber = { module = "com.jakewharton.timber:timber", version.ref = "com-jakewharton-timber-version" }
com-squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "com-squareup-retrofit2-retrofit-version" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit-version" }
junit = { module = "junit:junit", version.ref = "junit-version" }
androidx-test-espresso-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso-espresso-core-version" }
org-jetbrains-kotlinx-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx-version" }
org-jetbrains-kotlinx-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx-version" }
org-jetbrains-kotlinx-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "org-jetbrains-kotlinx-kotlinx-serialization-json-version" }
org-jetbrains-kotlinx-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "org-jetbrains-kotlinx-kotlinx-coroutines-test-version" }
androidx-hilt-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt-hilt-navigation-compose-version" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-version"}
androidx-compose-material-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose-version"}
androidx-compose-ui-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-version"}
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-activity-compose-version" }
androidx-navigation-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation-version" }
com-android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "com-android-tools-build-gradle-version" }
org-jetbrains-kotlin-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin-kotlin-gradle-plugin-version" }
org-jetbrains-kotlin-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "org-jetbrains-kotlin-kotlin-gradle-plugin-version" }
androidx-navigation-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation-version"}
androidx-arch-core-core-testing = { module =  "androidx.arch.core:core-testing", version.ref = "androidx-arch-core-core-testing-version" }
io-mockk = { module = "io.mockk:mockk", version.ref = "io-mockk-version" }
androidx-annotation = {module = "androidx.annotation:annotation", version.ref = "androidx-annotation-version" }
com-google-protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "com-google-protobuf-version" }

[plugins]
com-github-ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin-version" }
nl-littlerobots-version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "catalog-plugin-version" }
com-google-protobuf = { id = "com.google.protobuf", version.ref = "com-google-protobuf-version" }
