name: Build and Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Generate Build Number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ secrets.github_token }}
      - name: Print new build number
        run: echo "Build number [$BUILD_NUMBER]"

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
          cache: 'gradle'

      - name: Build the app
        run: ./gradlew assembleRelease --stacktrace
        env:
          alias: ${{ secrets.alias }}
          keyPass: ${{ secrets.keyPass }}
          store: ${{ secrets.store }}
          storePass: ${{ secrets.storePass }}
          rapid_api_key: ${{ secrets.rapid_api_key }}
          buildNumber: ${{ needs.setup.outputs.build_number }}

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
          cache: 'gradle'

      - name: Run tests
        run: ./gradlew testDebugUnitTest --stacktrace
        env:
          alias: ${{ secrets.alias }}
          keyPass: ${{ secrets.keyPass }}
          store: ${{ secrets.store }}
          storePass: ${{ secrets.storePass }}
          rapid_api_key: ${{ secrets.rapid_api_key }}
          buildNumber: 1

  detekt:
    name: Static Analysis - Detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
          cache: 'gradle'

      - name: Run detekt static analysis
        run: ./gradlew detektMain
        env:
          alias: ${{ secrets.alias }}
          keyPass: ${{ secrets.keyPass }}
          store: ${{ secrets.store }}
          storePass: ${{ secrets.storePass }}
          rapid_api_key: ${{ secrets.rapid_api_key }}
          buildNumber: 1

  lint:
    name: Static Analysis - Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
          cache: 'gradle'

      - name: Run lint static analysis
        run: ./gradlew lintDebug --stacktrace
        env:
          alias: ${{ secrets.alias }}
          keyPass: ${{ secrets.keyPass }}
          store: ${{ secrets.store }}
          storePass: ${{ secrets.storePass }}
          rapid_api_key: ${{ secrets.rapid_api_key }}
          buildNumber: 1
