name: Build and Test

on:
  push:
    branches: [ main, feature/compose ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
          cache: 'gradle'

      - name: Build the app
        run: ./gradlew buildDebug --stacktrace

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
          cache: 'gradle'

      - name: Run tests
        run: ./gradlew testDebugUnitTest --stacktrace

  analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
          cache: 'gradle'

      - name: Run ktlint static analysis
        run: ./gradlew ktlintcheck

      - name: Run lint static analysis
        run: ./gradlew lintDebug --stacktrace
