name: Build and Test

on:
  push:
    branches: [ main, feature/compose ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew buildDebug --stacktrace

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew testDebugUnitTest --stacktrace

  ktlint:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run static analysis
        run: ./gradlew ktlintcheck
