name: Main - Build and Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Generate Build Number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ secrets.github_token }}
      - name: Print new build number
        run: echo "Build number [$BUILD_NUMBER]"

  common:
    name: Common
    runs-on: ubuntu-latest
    uses: ./.github/workflows/setup_workflow.yml

  build:
    name: Build
    needs: [setup, common]
    runs-on: ubuntu-latest
    steps:
      - name: Build the app
        run: ./gradlew assembleRelease --stacktrace
        env:
          alias: ${{ secrets.alias }}
          keyPass: ${{ secrets.keyPass }}
          store: ${{ secrets.store }}
          storePass: ${{ secrets.storePass }}
          rapid_api_key: ${{ secrets.rapid_api_key }}
          buildNumber: ${{ needs.setup.outputs.build_number }}

  test:
    name: Unit Tests
    needs: common
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: ./gradlew testDebugUnitTest --stacktrace
        env:
          alias: ${{ secrets.alias }}
          keyPass: ${{ secrets.keyPass }}
          store: ${{ secrets.store }}
          storePass: ${{ secrets.storePass }}
          rapid_api_key: ${{ secrets.rapid_api_key }}
          buildNumber: 1

  detekt:
    name: Static Analysis - Detekt
    needs: common
    runs-on: ubuntu-latest
    steps:
      - name: Run detekt static analysis
        run: ./gradlew detektMain
        env:
          alias: ${{ secrets.alias }}
          keyPass: ${{ secrets.keyPass }}
          store: ${{ secrets.store }}
          storePass: ${{ secrets.storePass }}
          rapid_api_key: ${{ secrets.rapid_api_key }}
          buildNumber: 1

  lint:
    name: Static Analysis - Lint
    needs: common
    runs-on: ubuntu-latest
    steps:
      - name: Run lint static analysis
        run: ./gradlew lintDebug --stacktrace
        env:
          alias: ${{ secrets.alias }}
          keyPass: ${{ secrets.keyPass }}
          store: ${{ secrets.store }}
          storePass: ${{ secrets.storePass }}
          rapid_api_key: ${{ secrets.rapid_api_key }}
          buildNumber: 1
