name: PR Workflow

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build the app
        run: ./gradlew assembleRelease --stacktrace
        env:
          alias: ${{ secrets.alias }}
          keyPass: ${{ secrets.keyPass }}
          store: ${{ secrets.store }}
          storePass: ${{ secrets.storePass }}
          rapid_api_key: ${{ secrets.rapid_api_key }}
          buildNumber: 1

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: ./gradlew testDebugUnitTest --stacktrace
        env:
          alias: ${{ secrets.alias }}
          keyPass: ${{ secrets.keyPass }}
          store: ${{ secrets.store }}
          storePass: ${{ secrets.storePass }}
          rapid_api_key: ${{ secrets.rapid_api_key }}
          buildNumber: 1

  instrumentation:
    name: Instrumented tests
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run instrumented tests
        run: ./gradlew ciGroupDebugAndroidTest -Dorg.gradle.workers.max=1 -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
        env:
          alias: ${{ secrets.alias }}
          keyPass: ${{ secrets.keyPass }}
          store: ${{ secrets.store }}
          storePass: ${{ secrets.storePass }}
          rapid_api_key: ${{ secrets.rapid_api_key }}
          buildNumber: 1

  detekt:
    name: Static Analysis - Detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run detekt static analysis
        run: ./gradlew detektMain
        env:
          alias: ${{ secrets.alias }}
          keyPass: ${{ secrets.keyPass }}
          store: ${{ secrets.store }}
          storePass: ${{ secrets.storePass }}
          rapid_api_key: ${{ secrets.rapid_api_key }}
          buildNumber: 1

  lint:
    name: Static Analysis - Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run lint static analysis
        run: ./gradlew lintDebug --stacktrace
        env:
          alias: ${{ secrets.alias }}
          keyPass: ${{ secrets.keyPass }}
          store: ${{ secrets.store }}
          storePass: ${{ secrets.storePass }}
          rapid_api_key: ${{ secrets.rapid_api_key }}
          buildNumber: 1
